version: '3.8'

services:
  predict-app:
    build: .
    container_name: crypto-predict
    ports:
      - "1505:1505"
    environment:
      - NODE_ENV=production
      - PORT=1505
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:1505/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s